- Apps:
    - NAS:
        href: https://nas.titannium.fr
        icon: files

    - Secrets Pusher:
        href: https://secret.titannium.fr
        icon: https://www.google.com/s2/favicons?sz=128&domain=eu.pwpush.com

    - Recettes:
        href: https://recettes.titannium.fr
        icon: https://cdn-icons-png.flaticon.com/512/1830/1830839.png

    - Convertisseur YT:
        href: https://ytconvert.titannium.fr
        icon: https://media.sys.truenas.net/apps/metube/icons/icon.svg


- Streaming:
    - Disney+:
        href: https://disneyplus.com
        icon: disney-plus

    - Prime Video:
        href: https://primevideo.com
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Amazon_Prime_Video_logo_%282024%29.svg/960px-Amazon_Prime_Video_logo_%282024%29.svg.png

    - Max:
        href: https://max.com
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR4OX1IRchlKZFj_MD-8Qw9esdgUxlaNkZTA&s

    - Ikromi:
        href: https://ikromi.com
        icon: https://www.google.com/s2/favicons?sz=128&domain=ikromi.com


- Infrastructure & Monitoring:
    - Nginx Proxy Manager:
        href: https://npm.titannium.fr
        icon: npm

    - Portainer:
        href: https://portainer.titannium.fr
        icon: portainer

    - CrowdSec:
        href: https://app.crowdsec.net
        icon: https://upload.wikimedia.org/wikipedia/commons/b/b3/CS-logo.webp

    - Kuma:
        href: https://kuma.titannium.fr
        icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.svg


